language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/mariomans.jar -t mariomans/se234-lab10-backend  .
- docker push mariomans/se234-lab10-backend
- docker pull mariomans/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: tj07USGjF+sEM4GkwIxKk6VjME7GnFhYC5IDcUcr6HOtP3y0zPjbMmkpc3q2rNeWB+xxteAIX/a/IM/M4qaPB1ENbyr5MOqs5I93jkOS+Ety9bBgPbgadh4NmUEuYhfKx06gY8TRoJizLj2c+wUTn+/aIw5dqOlWmglvZ4DMZn4MlWTgKQviw1qOcEcI4DxcvSh7a8+GVKhiMwCiX5tXOwk6lyYhXWLHVhSCm/k1s5PqNV28SbU5hO2RmfnWV0xgFEfwj5PRHcHjf1MNNDp5g2GbjqNwOi7ddyXysUE9VMHPNu4grb6M01+xD4NyZG/XAX+K1m27qwrnCS6B4Y3T80mWc0/VBFBLuNTk8IN7bMOBOZec33O3B/kVSTrhuc+G4CRoppQWtqXgDTVt7m2ve+BIZuo3heJESHr6rDpcF61PJT+Ye3NzfusUejDcKC3CJMcJAqhqu9u6nO/BNaSd70HQRprjxj058jCxWEDNCmACGvGMC5SAsUGhK4rxl2w+zXZMH/s2t6xxDJUFRKMM4c8u+LbenDh/nugt7Vu6gWUw/TAovu5if0+8UDhVFPzS8blXydRSgO/DBaDRdGo1YOfnSwwBwqtAI3HDsv4M+sZXoR8q8lLbdyOIIPSKhMTCfdNxEtYd5LPOLH3tUDRTYLE4V+xdLcklrVwVqouDjoM=
  - secure: CymgkV9bIrLOhCYluu73WY9bGpjkp03iDlEwqOGNUD//M337Ea7EzJWG7TUsRZzkZIGqlge5xkCSxot0E9kDuswmCPGLqNg3Qzv1hS+ZRukcISVa888Jrl9HROv6JzhixC4rUWc4QKW5+g7yIo0Ll96T/orMoS9AMZS2As6S00HoVc83yt4SsxYaFIm6+ntFbKaknh4odlyKOgWmEOGrB9OruKKsZw9jpIFsYODzfYhAyWYOhqJAEziktl1hupYbnRmeLas086ccSaupcLOXWlVD+/8SJ7VJUCfOP8xGywCW67wXF1LdrTO6NfApF1b7LSrpmx7csDnjgWf7nt2UocK3PeQL3xXgt9++hWUQmUW8iE41207lkeAzw4vFyX0JSSNns3rnWWW1HX405/Cj56hEbQLP/nxQmFR9m3sb8P2dEIhktOu8nuj4k66xnGvuucr5hjUKlyKnmn4DP6JigSNFoFxYjji7C1Jn6mneLz1gDAo9Z7kaJSbv5F1Ua5eQHme1+rong/z/BymwAni3jyeORRNfCg8TI1Mi3ZNm8MBwClqAl7Gdmk6yd+8YHS6ZvFPNvwuztmJ8L2Xwhjod1N4ye33AlktYyeyWD4gSFWvXL+HqgcjeeAE9f2ojrnnmxH3zHPocVDVM6mHJPCuvIb4dEHQ9z5fa/E5XAwCqLDU=
  - secure: EAgJ+GFsiJ7LHXi0gBF1NoeKYWHo9Q0f/miKjeSEd/ycWLDsdNBLg6q1bn53kRUxbl2mAmmZWeRMdhjQyH3l4yFnUsDx7l2kCnr28QScKMJo/t2FqXV9W4fRKQRfDlvZdiwzj2RLE4RsCjjYcstY5/lnnXZs/3S8oj185GfUHeF41kTgMwRYxrnWMOctQaIVbIFOU8TpSNUhmQUIIMZ++b8xWonoP/wKJw3aie9nAzswC4J31i7FDVO3Ugyqw7GV5wpZu+SrUGbNBjG4kJPir8NOOt9hq6KlSVR8OMuKQ1+vLrNTwTrRZQAvRtlNWfWt2vYaGXmeMwXTPAoO5oxGE9M738HSNfI+/gv9JbOBIByqo1xcAqLRSButrnODrCApuuUIGTRikzjq2VF2A0Kg9k8Wr4wNaQwFfZXke61pI55DydfyLI+YNpSy2Hg4wqBs4fggB9f9F8uXN8/YklHMI9uQYNPGiYn1fGy38tnrDpI1f14MW27LjfosDpD0nn7X1r3qsvwDA6XQM1YcYKeGCWAFjqnZvnofl/3zaquyZR2CFyfRpuXJnraLxN3TTfqVdoB8GAos0bkAS+tgFozbLa5yuLF78s9NvjcziTz6S4DZJanlb9lEtZrbU8mtGlPExCEBei4XSgz60kRnYnAZrukTK0DqoLfxwPzhdxUOfxI=
