language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/mariomans.jar -t mariomans/se234-lab10-backend  .
- docker push mariomans/se234-lab10-backend
- docker pull mariomans/se234-lab10-client
jdk:
- oraclejdk8
script:
- docker-compose -H "$DOCKER_HOST" up -d
- mvn test
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: iaw3bcPT7YhOufPrb+ylPC8qn8hPDTbkNUnCAT5rHZega2iF6NVaOrbtb0I7et7UfneA67RrIxZjPcRIar0FPhhmBh7pygvVtnnKPN6+RnZL7MXN01bFyv7+fG2yPFmAXVuE3Iw0BKDyb4pv4fifiwzS5Ztls96iZw4lmWAbAVkwH8Hv0AK+ZqG/OemwIY4IX5JLSL77oBPHf67e2GDTW/kvk1O5ftylOOKz9QbG/blGp9nd79KEeFZ3U8wObF5+vDcDrnZUwOyok/UIfdTSvfpMKuEYf8r4APglOOyHyUdBmzxJfXAPiUg1b2H9LgDbYw5jlrLFwsdplumI+HazWpVPK8GwSmyaviVHhLbuMqBllWUFtJgIo5MlhmS28AyczA3Cy17YhzyQ9uyuFdqFEeA3QyLTY2CJ/Wr/Kvg3C/o/6oaC0lPN58QYtmBzAwsPVr61TU7F9K8zg/tmH5786L16xZoqoQgmE2FU0/eoODsqXnSjbR8i/xlvawhhr4ZU080WeV8wu6vevO8kURxdVpFItlIsaZVTMEP+/CLfvHxYD+hex3HxLCUVthepXQjhPBsSnDC0bXawMaR4sdBxzoUl7eLJ9lYowpnPQ8ZG1NAzqSwK/MyhHoRgBonQlhr3QCgrISKxpU7KDpIZ+5Wbj8SJtwNrvdOo0YDrU4wycL4=
  - secure: kluQzkWerW+1SlCE7SJQ7Gv+6IdrGW6qD6sESK1lwJSCYPxhAx4IsdEWPZDnFh/Ekrd03IvpTAjlOhjkTdGY8luh5yjd171BwV0W2IfQn81A0oFvNBOKhBz0T+GE/DP1zM4zVZJTJMX1v74XGX6HZzbJFWXsIOSzxsdIyPWqPficSswKQXwJm1WHyDfXG3BDDG7ISkshJV6ayAgLGUn5r/8zTKBDlphsGkGaKMLayouRyZL9DHbuTb5CZ5gLOES1IPD3/1J4Dhx5NQMcQaLF/yD8fYL3094u9yEJluEBa2A/qKD+PCVnHYWZP5Uu48OBgxF615LbVEFXil/f8KmeL2bxvTduxljMAWL+zlA7J7ILNj/Xg6aCWVr0Z75PqH3MS7u7Iq43H2LmBNhkIEEW5ypxd7wjqXBh6TzUR0YoE3MFMJ/Lxn/EMOagep3PcRUx9k7RMphcpb0PEcB3B8rZzNwIwcOSRbxmUGYy3Y//140ijEj1Bp9yK/qFtyojMqDcPj8lfS4TcOuSuKIihArJ73wNRzfsGr7kRHGMjXm6mJ4dI+ZfRFimAtq3drR+IgNF+wZq6Sr/US0zwZf1vAOg7K6J3u7TtZiXyBnl2QT0gAOZFxACbkVGB52XWdCJIIrQGggpgggrbtckNaixhLpaPMRkk+x0oNed0bFlDmYI3+Y=
  - secure: SnqK2cu291cgpWQwh3GkYIEMUCps41txfFuXfq5jKDpP0K7TWq8pOh9yy2O1Ffk895/NthQy/qg3TxDsczx9oomJAXckVYvkDkbmRVa95Ka+N6StRVbAmcZKBNS5ffvuKLqJTODdhvOwU4jkHLZ8nDzpoNWQ7WQkq7TzvJt1mbzrPAPX3sUgoG0YV6rxx6ChwPWfwo+ivstaFb8Em1RiVzSwGuPqEvHU/FufixsRJn5opTaYQDf2nZpddSeiVY9Whn9a3StkC+8XGZJYtlYMebPkVyOgePqCAhZ3sKhEA4ANR6kjWUPm+8HO8Ha3i8Fe8+o8KLQaD+9DoygiuFNKQIEUGtGp1IgPh1FnvX3nV3fG1oLfiGwHRiRBE5Yrq757P1zxW0b1HQKu6EklhH5UVPWPDNMnledAU5ePpCrbpn5I1UAfOh0E8av7bct702DSOAD1e0bnF2Cf3E7uaJbH5CJiQs2kVG3DnfkNJNjZFIZL4OpK/Cnp8Ly8uXy0AgPM0fB4sDUnvOHKwYeqQ+ySrkTDbuR7qKxmdanW0rHJKa63m0gTfv4kJ1IahU0SDPCRrbmjblwWWk+n2qf72uqEwaJu5ALbxBWqqnRUMsxkUXSwsqq198tCDEjIQbYN6dtiYukFeYYyvkr4Qk/5+mrl1WVFEHrtI4EYE9nTSDxo32I=
